model_name: linkml-example-model
model_py_name: linkml_example_model
root_schema: example

model_organization: linkml
model_author: Jane Author
model_author_email: janea@example.org
model_synopsis: An example of a LinkML model
model_description: |-
  A simple example of a LinkML model

# Trove Classifiers (https://pypi.org/classifiers/) -- copied to setup.cfg only if not already present
classifiers:
    - "Development Status :: 4 - Beta"
    - "Environment :: Console"
    - "Intended Audience :: Developers"
    - "Intended Audience :: Science/Research"
    - "Intended Audience :: Healthcare Industry"
    - "License :: CC0 1.0 Universal (CC0 1.0) Public Domain Dedication"
    - "Programming Language :: Python :: 3 :: Only"
    - "Programming Language :: Python :: 3.7"
    - "Programming Language :: Python :: 3.8"
    - "Programming Language :: Python :: 3.9"

# Keywords -- copied to setup.cfg only if not already present
keywords: [linkml, LOD, Modeling, Linked open data, model]

# Elements to be generated
# See: https://github.com/linkml/linkml/generators/README.md for what the outputs look like
# Possible values: graphql -- graphql schema for the model
#                  json -- LinkML model definition in JSON syntax
#                  jsonld_context -- JSON-LD context definitions for model
#                  json_schema -- Model schema in json schema
#                  owl -- OWL representation of model schema
#                  rdf -- LinkML Model definition in RDF
#                  shex -- LinkML model definition in ShEx
generate: [graphql, json, jsonld_context, json_schema, rdf, shex]

